// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: direction_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from direction_data.proto</summary>
public static partial class DirectionDataReflection {

  #region Descriptor
  /// <summary>File descriptor for direction_data.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static DirectionDataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChRkaXJlY3Rpb25fZGF0YS5wcm90byK3AQoNRGlyZWN0aW9uRGF0YRITCglk",
          "ZXN0X2Rpc3QYASABKAk6ABIXCg1kZXN0X2R1cmF0aW9uGAIgASgJOgASEwoJ",
          "Y3Vycl9kaXN0GAMgASgJOgASFwoNY3Vycl9kdXJhdGlvbhgEIAEoCToAEhQK",
          "CmN1cnJfaW5zdHIYBSABKAk6ABIYCg5jdXJyX2RpcmVjdGlvbhgGIAEoCToA",
          "EhoKC2F1ZGlvX2luc3RyGAcgASgIOgVmYWxzZQ=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::DirectionData), global::DirectionData.Parser, new[]{ "DestDist", "DestDuration", "CurrDist", "CurrDuration", "CurrInstr", "CurrDirection", "AudioInstr" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class DirectionData : pb::IMessage<DirectionData>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<DirectionData> _parser = new pb::MessageParser<DirectionData>(() => new DirectionData());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<DirectionData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DirectionDataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DirectionData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DirectionData(DirectionData other) : this() {
    _hasBits0 = other._hasBits0;
    destDist_ = other.destDist_;
    destDuration_ = other.destDuration_;
    currDist_ = other.currDist_;
    currDuration_ = other.currDuration_;
    currInstr_ = other.currInstr_;
    currDirection_ = other.currDirection_;
    audioInstr_ = other.audioInstr_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DirectionData Clone() {
    return new DirectionData(this);
  }

  /// <summary>Field number for the "dest_dist" field.</summary>
  public const int DestDistFieldNumber = 1;
  private readonly static string DestDistDefaultValue = "";

  private string destDist_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string DestDist {
    get { return destDist_ ?? DestDistDefaultValue; }
    set {
      destDist_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "dest_dist" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasDestDist {
    get { return destDist_ != null; }
  }
  /// <summary>Clears the value of the "dest_dist" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearDestDist() {
    destDist_ = null;
  }

  /// <summary>Field number for the "dest_duration" field.</summary>
  public const int DestDurationFieldNumber = 2;
  private readonly static string DestDurationDefaultValue = "";

  private string destDuration_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string DestDuration {
    get { return destDuration_ ?? DestDurationDefaultValue; }
    set {
      destDuration_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "dest_duration" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasDestDuration {
    get { return destDuration_ != null; }
  }
  /// <summary>Clears the value of the "dest_duration" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearDestDuration() {
    destDuration_ = null;
  }

  /// <summary>Field number for the "curr_dist" field.</summary>
  public const int CurrDistFieldNumber = 3;
  private readonly static string CurrDistDefaultValue = "";

  private string currDist_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string CurrDist {
    get { return currDist_ ?? CurrDistDefaultValue; }
    set {
      currDist_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "curr_dist" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasCurrDist {
    get { return currDist_ != null; }
  }
  /// <summary>Clears the value of the "curr_dist" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearCurrDist() {
    currDist_ = null;
  }

  /// <summary>Field number for the "curr_duration" field.</summary>
  public const int CurrDurationFieldNumber = 4;
  private readonly static string CurrDurationDefaultValue = "";

  private string currDuration_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string CurrDuration {
    get { return currDuration_ ?? CurrDurationDefaultValue; }
    set {
      currDuration_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "curr_duration" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasCurrDuration {
    get { return currDuration_ != null; }
  }
  /// <summary>Clears the value of the "curr_duration" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearCurrDuration() {
    currDuration_ = null;
  }

  /// <summary>Field number for the "curr_instr" field.</summary>
  public const int CurrInstrFieldNumber = 5;
  private readonly static string CurrInstrDefaultValue = "";

  private string currInstr_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string CurrInstr {
    get { return currInstr_ ?? CurrInstrDefaultValue; }
    set {
      currInstr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "curr_instr" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasCurrInstr {
    get { return currInstr_ != null; }
  }
  /// <summary>Clears the value of the "curr_instr" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearCurrInstr() {
    currInstr_ = null;
  }

  /// <summary>Field number for the "curr_direction" field.</summary>
  public const int CurrDirectionFieldNumber = 6;
  private readonly static string CurrDirectionDefaultValue = "";

  private string currDirection_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string CurrDirection {
    get { return currDirection_ ?? CurrDirectionDefaultValue; }
    set {
      currDirection_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "curr_direction" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasCurrDirection {
    get { return currDirection_ != null; }
  }
  /// <summary>Clears the value of the "curr_direction" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearCurrDirection() {
    currDirection_ = null;
  }

  /// <summary>Field number for the "audio_instr" field.</summary>
  public const int AudioInstrFieldNumber = 7;
  private readonly static bool AudioInstrDefaultValue = false;

  private bool audioInstr_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool AudioInstr {
    get { if ((_hasBits0 & 1) != 0) { return audioInstr_; } else { return AudioInstrDefaultValue; } }
    set {
      _hasBits0 |= 1;
      audioInstr_ = value;
    }
  }
  /// <summary>Gets whether the "audio_instr" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasAudioInstr {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "audio_instr" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearAudioInstr() {
    _hasBits0 &= ~1;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as DirectionData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(DirectionData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (DestDist != other.DestDist) return false;
    if (DestDuration != other.DestDuration) return false;
    if (CurrDist != other.CurrDist) return false;
    if (CurrDuration != other.CurrDuration) return false;
    if (CurrInstr != other.CurrInstr) return false;
    if (CurrDirection != other.CurrDirection) return false;
    if (AudioInstr != other.AudioInstr) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasDestDist) hash ^= DestDist.GetHashCode();
    if (HasDestDuration) hash ^= DestDuration.GetHashCode();
    if (HasCurrDist) hash ^= CurrDist.GetHashCode();
    if (HasCurrDuration) hash ^= CurrDuration.GetHashCode();
    if (HasCurrInstr) hash ^= CurrInstr.GetHashCode();
    if (HasCurrDirection) hash ^= CurrDirection.GetHashCode();
    if (HasAudioInstr) hash ^= AudioInstr.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasDestDist) {
      output.WriteRawTag(10);
      output.WriteString(DestDist);
    }
    if (HasDestDuration) {
      output.WriteRawTag(18);
      output.WriteString(DestDuration);
    }
    if (HasCurrDist) {
      output.WriteRawTag(26);
      output.WriteString(CurrDist);
    }
    if (HasCurrDuration) {
      output.WriteRawTag(34);
      output.WriteString(CurrDuration);
    }
    if (HasCurrInstr) {
      output.WriteRawTag(42);
      output.WriteString(CurrInstr);
    }
    if (HasCurrDirection) {
      output.WriteRawTag(50);
      output.WriteString(CurrDirection);
    }
    if (HasAudioInstr) {
      output.WriteRawTag(56);
      output.WriteBool(AudioInstr);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasDestDist) {
      output.WriteRawTag(10);
      output.WriteString(DestDist);
    }
    if (HasDestDuration) {
      output.WriteRawTag(18);
      output.WriteString(DestDuration);
    }
    if (HasCurrDist) {
      output.WriteRawTag(26);
      output.WriteString(CurrDist);
    }
    if (HasCurrDuration) {
      output.WriteRawTag(34);
      output.WriteString(CurrDuration);
    }
    if (HasCurrInstr) {
      output.WriteRawTag(42);
      output.WriteString(CurrInstr);
    }
    if (HasCurrDirection) {
      output.WriteRawTag(50);
      output.WriteString(CurrDirection);
    }
    if (HasAudioInstr) {
      output.WriteRawTag(56);
      output.WriteBool(AudioInstr);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasDestDist) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(DestDist);
    }
    if (HasDestDuration) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(DestDuration);
    }
    if (HasCurrDist) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(CurrDist);
    }
    if (HasCurrDuration) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(CurrDuration);
    }
    if (HasCurrInstr) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(CurrInstr);
    }
    if (HasCurrDirection) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(CurrDirection);
    }
    if (HasAudioInstr) {
      size += 1 + 1;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(DirectionData other) {
    if (other == null) {
      return;
    }
    if (other.HasDestDist) {
      DestDist = other.DestDist;
    }
    if (other.HasDestDuration) {
      DestDuration = other.DestDuration;
    }
    if (other.HasCurrDist) {
      CurrDist = other.CurrDist;
    }
    if (other.HasCurrDuration) {
      CurrDuration = other.CurrDuration;
    }
    if (other.HasCurrInstr) {
      CurrInstr = other.CurrInstr;
    }
    if (other.HasCurrDirection) {
      CurrDirection = other.CurrDirection;
    }
    if (other.HasAudioInstr) {
      AudioInstr = other.AudioInstr;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          DestDist = input.ReadString();
          break;
        }
        case 18: {
          DestDuration = input.ReadString();
          break;
        }
        case 26: {
          CurrDist = input.ReadString();
          break;
        }
        case 34: {
          CurrDuration = input.ReadString();
          break;
        }
        case 42: {
          CurrInstr = input.ReadString();
          break;
        }
        case 50: {
          CurrDirection = input.ReadString();
          break;
        }
        case 56: {
          AudioInstr = input.ReadBool();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          DestDist = input.ReadString();
          break;
        }
        case 18: {
          DestDuration = input.ReadString();
          break;
        }
        case 26: {
          CurrDist = input.ReadString();
          break;
        }
        case 34: {
          CurrDuration = input.ReadString();
          break;
        }
        case 42: {
          CurrInstr = input.ReadString();
          break;
        }
        case 50: {
          CurrDirection = input.ReadString();
          break;
        }
        case 56: {
          AudioInstr = input.ReadBool();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
