// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: running_type_position_mapping_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from running_type_position_mapping_data.proto</summary>
public static partial class RunningTypePositionMappingDataReflection {

  #region Descriptor
  /// <summary>File descriptor for running_type_position_mapping_data.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static RunningTypePositionMappingDataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CihydW5uaW5nX3R5cGVfcG9zaXRpb25fbWFwcGluZ19kYXRhLnByb3RvIoEE",
          "Ch5SdW5uaW5nVHlwZVBvc2l0aW9uTWFwcGluZ0RhdGESJAoZcnVubmluZ19k",
          "aXN0YW5jZV9wb3NpdGlvbhgBIAEoBToBNBIhChZydW5uaW5nX3NwZWVkX3Bv",
          "c2l0aW9uGAIgASgFOgExEiQKGXJ1bm5pbmdfY2Fsb3JpZXNfcG9zaXRpb24Y",
          "AyABKAU6ATISJgobcnVubmluZ19oZWFydF9yYXRlX3Bvc2l0aW9uGAQgASgF",
          "OgEzEiQKGXJ1bm5pbmdfZHVyYXRpb25fcG9zaXRpb24YBSABKAU6ATcSIAoV",
          "cnVubmluZ190aW1lX3Bvc2l0aW9uGAYgASgFOgE1EiIKF3N1bW1hcnlfZGV0",
          "YWlsX3Bvc2l0aW9uGAcgASgFOgEwEiQKGXN1bW1hcnlfZGlzdGFuY2VfcG9z",
          "aXRpb24YCCABKAU6ATESIQoWc3VtbWFyeV9zcGVlZF9wb3NpdGlvbhgJIAEo",
          "BToBMhIkChlzdW1tYXJ5X2R1cmF0aW9uX3Bvc2l0aW9uGAogASgFOgEzEiAK",
          "FXN1bW1hcnlfdGltZV9wb3NpdGlvbhgLIAEoBToBNRIjChhzZWxlY3Rpb25f",
          "c3BlZWRfcG9zaXRpb24YDCABKAU6ATcSJgobc2VsZWN0aW9uX2Rpc3RhbmNl",
          "X3Bvc2l0aW9uGA0gASgFOgE4"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::RunningTypePositionMappingData), global::RunningTypePositionMappingData.Parser, new[]{ "RunningDistancePosition", "RunningSpeedPosition", "RunningCaloriesPosition", "RunningHeartRatePosition", "RunningDurationPosition", "RunningTimePosition", "SummaryDetailPosition", "SummaryDistancePosition", "SummarySpeedPosition", "SummaryDurationPosition", "SummaryTimePosition", "SelectionSpeedPosition", "SelectionDistancePosition" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class RunningTypePositionMappingData : pb::IMessage<RunningTypePositionMappingData>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<RunningTypePositionMappingData> _parser = new pb::MessageParser<RunningTypePositionMappingData>(() => new RunningTypePositionMappingData());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<RunningTypePositionMappingData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RunningTypePositionMappingDataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RunningTypePositionMappingData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RunningTypePositionMappingData(RunningTypePositionMappingData other) : this() {
    _hasBits0 = other._hasBits0;
    runningDistancePosition_ = other.runningDistancePosition_;
    runningSpeedPosition_ = other.runningSpeedPosition_;
    runningCaloriesPosition_ = other.runningCaloriesPosition_;
    runningHeartRatePosition_ = other.runningHeartRatePosition_;
    runningDurationPosition_ = other.runningDurationPosition_;
    runningTimePosition_ = other.runningTimePosition_;
    summaryDetailPosition_ = other.summaryDetailPosition_;
    summaryDistancePosition_ = other.summaryDistancePosition_;
    summarySpeedPosition_ = other.summarySpeedPosition_;
    summaryDurationPosition_ = other.summaryDurationPosition_;
    summaryTimePosition_ = other.summaryTimePosition_;
    selectionSpeedPosition_ = other.selectionSpeedPosition_;
    selectionDistancePosition_ = other.selectionDistancePosition_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RunningTypePositionMappingData Clone() {
    return new RunningTypePositionMappingData(this);
  }

  /// <summary>Field number for the "running_distance_position" field.</summary>
  public const int RunningDistancePositionFieldNumber = 1;
  private readonly static int RunningDistancePositionDefaultValue = 4;

  private int runningDistancePosition_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int RunningDistancePosition {
    get { if ((_hasBits0 & 1) != 0) { return runningDistancePosition_; } else { return RunningDistancePositionDefaultValue; } }
    set {
      _hasBits0 |= 1;
      runningDistancePosition_ = value;
    }
  }
  /// <summary>Gets whether the "running_distance_position" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasRunningDistancePosition {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "running_distance_position" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearRunningDistancePosition() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "running_speed_position" field.</summary>
  public const int RunningSpeedPositionFieldNumber = 2;
  private readonly static int RunningSpeedPositionDefaultValue = 1;

  private int runningSpeedPosition_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int RunningSpeedPosition {
    get { if ((_hasBits0 & 2) != 0) { return runningSpeedPosition_; } else { return RunningSpeedPositionDefaultValue; } }
    set {
      _hasBits0 |= 2;
      runningSpeedPosition_ = value;
    }
  }
  /// <summary>Gets whether the "running_speed_position" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasRunningSpeedPosition {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "running_speed_position" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearRunningSpeedPosition() {
    _hasBits0 &= ~2;
  }

  /// <summary>Field number for the "running_calories_position" field.</summary>
  public const int RunningCaloriesPositionFieldNumber = 3;
  private readonly static int RunningCaloriesPositionDefaultValue = 2;

  private int runningCaloriesPosition_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int RunningCaloriesPosition {
    get { if ((_hasBits0 & 4) != 0) { return runningCaloriesPosition_; } else { return RunningCaloriesPositionDefaultValue; } }
    set {
      _hasBits0 |= 4;
      runningCaloriesPosition_ = value;
    }
  }
  /// <summary>Gets whether the "running_calories_position" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasRunningCaloriesPosition {
    get { return (_hasBits0 & 4) != 0; }
  }
  /// <summary>Clears the value of the "running_calories_position" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearRunningCaloriesPosition() {
    _hasBits0 &= ~4;
  }

  /// <summary>Field number for the "running_heart_rate_position" field.</summary>
  public const int RunningHeartRatePositionFieldNumber = 4;
  private readonly static int RunningHeartRatePositionDefaultValue = 3;

  private int runningHeartRatePosition_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int RunningHeartRatePosition {
    get { if ((_hasBits0 & 8) != 0) { return runningHeartRatePosition_; } else { return RunningHeartRatePositionDefaultValue; } }
    set {
      _hasBits0 |= 8;
      runningHeartRatePosition_ = value;
    }
  }
  /// <summary>Gets whether the "running_heart_rate_position" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasRunningHeartRatePosition {
    get { return (_hasBits0 & 8) != 0; }
  }
  /// <summary>Clears the value of the "running_heart_rate_position" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearRunningHeartRatePosition() {
    _hasBits0 &= ~8;
  }

  /// <summary>Field number for the "running_duration_position" field.</summary>
  public const int RunningDurationPositionFieldNumber = 5;
  private readonly static int RunningDurationPositionDefaultValue = 7;

  private int runningDurationPosition_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int RunningDurationPosition {
    get { if ((_hasBits0 & 16) != 0) { return runningDurationPosition_; } else { return RunningDurationPositionDefaultValue; } }
    set {
      _hasBits0 |= 16;
      runningDurationPosition_ = value;
    }
  }
  /// <summary>Gets whether the "running_duration_position" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasRunningDurationPosition {
    get { return (_hasBits0 & 16) != 0; }
  }
  /// <summary>Clears the value of the "running_duration_position" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearRunningDurationPosition() {
    _hasBits0 &= ~16;
  }

  /// <summary>Field number for the "running_time_position" field.</summary>
  public const int RunningTimePositionFieldNumber = 6;
  private readonly static int RunningTimePositionDefaultValue = 5;

  private int runningTimePosition_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int RunningTimePosition {
    get { if ((_hasBits0 & 32) != 0) { return runningTimePosition_; } else { return RunningTimePositionDefaultValue; } }
    set {
      _hasBits0 |= 32;
      runningTimePosition_ = value;
    }
  }
  /// <summary>Gets whether the "running_time_position" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasRunningTimePosition {
    get { return (_hasBits0 & 32) != 0; }
  }
  /// <summary>Clears the value of the "running_time_position" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearRunningTimePosition() {
    _hasBits0 &= ~32;
  }

  /// <summary>Field number for the "summary_detail_position" field.</summary>
  public const int SummaryDetailPositionFieldNumber = 7;
  private readonly static int SummaryDetailPositionDefaultValue = 0;

  private int summaryDetailPosition_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int SummaryDetailPosition {
    get { if ((_hasBits0 & 64) != 0) { return summaryDetailPosition_; } else { return SummaryDetailPositionDefaultValue; } }
    set {
      _hasBits0 |= 64;
      summaryDetailPosition_ = value;
    }
  }
  /// <summary>Gets whether the "summary_detail_position" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasSummaryDetailPosition {
    get { return (_hasBits0 & 64) != 0; }
  }
  /// <summary>Clears the value of the "summary_detail_position" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearSummaryDetailPosition() {
    _hasBits0 &= ~64;
  }

  /// <summary>Field number for the "summary_distance_position" field.</summary>
  public const int SummaryDistancePositionFieldNumber = 8;
  private readonly static int SummaryDistancePositionDefaultValue = 1;

  private int summaryDistancePosition_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int SummaryDistancePosition {
    get { if ((_hasBits0 & 128) != 0) { return summaryDistancePosition_; } else { return SummaryDistancePositionDefaultValue; } }
    set {
      _hasBits0 |= 128;
      summaryDistancePosition_ = value;
    }
  }
  /// <summary>Gets whether the "summary_distance_position" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasSummaryDistancePosition {
    get { return (_hasBits0 & 128) != 0; }
  }
  /// <summary>Clears the value of the "summary_distance_position" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearSummaryDistancePosition() {
    _hasBits0 &= ~128;
  }

  /// <summary>Field number for the "summary_speed_position" field.</summary>
  public const int SummarySpeedPositionFieldNumber = 9;
  private readonly static int SummarySpeedPositionDefaultValue = 2;

  private int summarySpeedPosition_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int SummarySpeedPosition {
    get { if ((_hasBits0 & 256) != 0) { return summarySpeedPosition_; } else { return SummarySpeedPositionDefaultValue; } }
    set {
      _hasBits0 |= 256;
      summarySpeedPosition_ = value;
    }
  }
  /// <summary>Gets whether the "summary_speed_position" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasSummarySpeedPosition {
    get { return (_hasBits0 & 256) != 0; }
  }
  /// <summary>Clears the value of the "summary_speed_position" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearSummarySpeedPosition() {
    _hasBits0 &= ~256;
  }

  /// <summary>Field number for the "summary_duration_position" field.</summary>
  public const int SummaryDurationPositionFieldNumber = 10;
  private readonly static int SummaryDurationPositionDefaultValue = 3;

  private int summaryDurationPosition_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int SummaryDurationPosition {
    get { if ((_hasBits0 & 512) != 0) { return summaryDurationPosition_; } else { return SummaryDurationPositionDefaultValue; } }
    set {
      _hasBits0 |= 512;
      summaryDurationPosition_ = value;
    }
  }
  /// <summary>Gets whether the "summary_duration_position" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasSummaryDurationPosition {
    get { return (_hasBits0 & 512) != 0; }
  }
  /// <summary>Clears the value of the "summary_duration_position" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearSummaryDurationPosition() {
    _hasBits0 &= ~512;
  }

  /// <summary>Field number for the "summary_time_position" field.</summary>
  public const int SummaryTimePositionFieldNumber = 11;
  private readonly static int SummaryTimePositionDefaultValue = 5;

  private int summaryTimePosition_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int SummaryTimePosition {
    get { if ((_hasBits0 & 1024) != 0) { return summaryTimePosition_; } else { return SummaryTimePositionDefaultValue; } }
    set {
      _hasBits0 |= 1024;
      summaryTimePosition_ = value;
    }
  }
  /// <summary>Gets whether the "summary_time_position" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasSummaryTimePosition {
    get { return (_hasBits0 & 1024) != 0; }
  }
  /// <summary>Clears the value of the "summary_time_position" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearSummaryTimePosition() {
    _hasBits0 &= ~1024;
  }

  /// <summary>Field number for the "selection_speed_position" field.</summary>
  public const int SelectionSpeedPositionFieldNumber = 12;
  private readonly static int SelectionSpeedPositionDefaultValue = 7;

  private int selectionSpeedPosition_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int SelectionSpeedPosition {
    get { if ((_hasBits0 & 2048) != 0) { return selectionSpeedPosition_; } else { return SelectionSpeedPositionDefaultValue; } }
    set {
      _hasBits0 |= 2048;
      selectionSpeedPosition_ = value;
    }
  }
  /// <summary>Gets whether the "selection_speed_position" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasSelectionSpeedPosition {
    get { return (_hasBits0 & 2048) != 0; }
  }
  /// <summary>Clears the value of the "selection_speed_position" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearSelectionSpeedPosition() {
    _hasBits0 &= ~2048;
  }

  /// <summary>Field number for the "selection_distance_position" field.</summary>
  public const int SelectionDistancePositionFieldNumber = 13;
  private readonly static int SelectionDistancePositionDefaultValue = 8;

  private int selectionDistancePosition_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int SelectionDistancePosition {
    get { if ((_hasBits0 & 4096) != 0) { return selectionDistancePosition_; } else { return SelectionDistancePositionDefaultValue; } }
    set {
      _hasBits0 |= 4096;
      selectionDistancePosition_ = value;
    }
  }
  /// <summary>Gets whether the "selection_distance_position" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasSelectionDistancePosition {
    get { return (_hasBits0 & 4096) != 0; }
  }
  /// <summary>Clears the value of the "selection_distance_position" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearSelectionDistancePosition() {
    _hasBits0 &= ~4096;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as RunningTypePositionMappingData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(RunningTypePositionMappingData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (RunningDistancePosition != other.RunningDistancePosition) return false;
    if (RunningSpeedPosition != other.RunningSpeedPosition) return false;
    if (RunningCaloriesPosition != other.RunningCaloriesPosition) return false;
    if (RunningHeartRatePosition != other.RunningHeartRatePosition) return false;
    if (RunningDurationPosition != other.RunningDurationPosition) return false;
    if (RunningTimePosition != other.RunningTimePosition) return false;
    if (SummaryDetailPosition != other.SummaryDetailPosition) return false;
    if (SummaryDistancePosition != other.SummaryDistancePosition) return false;
    if (SummarySpeedPosition != other.SummarySpeedPosition) return false;
    if (SummaryDurationPosition != other.SummaryDurationPosition) return false;
    if (SummaryTimePosition != other.SummaryTimePosition) return false;
    if (SelectionSpeedPosition != other.SelectionSpeedPosition) return false;
    if (SelectionDistancePosition != other.SelectionDistancePosition) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasRunningDistancePosition) hash ^= RunningDistancePosition.GetHashCode();
    if (HasRunningSpeedPosition) hash ^= RunningSpeedPosition.GetHashCode();
    if (HasRunningCaloriesPosition) hash ^= RunningCaloriesPosition.GetHashCode();
    if (HasRunningHeartRatePosition) hash ^= RunningHeartRatePosition.GetHashCode();
    if (HasRunningDurationPosition) hash ^= RunningDurationPosition.GetHashCode();
    if (HasRunningTimePosition) hash ^= RunningTimePosition.GetHashCode();
    if (HasSummaryDetailPosition) hash ^= SummaryDetailPosition.GetHashCode();
    if (HasSummaryDistancePosition) hash ^= SummaryDistancePosition.GetHashCode();
    if (HasSummarySpeedPosition) hash ^= SummarySpeedPosition.GetHashCode();
    if (HasSummaryDurationPosition) hash ^= SummaryDurationPosition.GetHashCode();
    if (HasSummaryTimePosition) hash ^= SummaryTimePosition.GetHashCode();
    if (HasSelectionSpeedPosition) hash ^= SelectionSpeedPosition.GetHashCode();
    if (HasSelectionDistancePosition) hash ^= SelectionDistancePosition.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasRunningDistancePosition) {
      output.WriteRawTag(8);
      output.WriteInt32(RunningDistancePosition);
    }
    if (HasRunningSpeedPosition) {
      output.WriteRawTag(16);
      output.WriteInt32(RunningSpeedPosition);
    }
    if (HasRunningCaloriesPosition) {
      output.WriteRawTag(24);
      output.WriteInt32(RunningCaloriesPosition);
    }
    if (HasRunningHeartRatePosition) {
      output.WriteRawTag(32);
      output.WriteInt32(RunningHeartRatePosition);
    }
    if (HasRunningDurationPosition) {
      output.WriteRawTag(40);
      output.WriteInt32(RunningDurationPosition);
    }
    if (HasRunningTimePosition) {
      output.WriteRawTag(48);
      output.WriteInt32(RunningTimePosition);
    }
    if (HasSummaryDetailPosition) {
      output.WriteRawTag(56);
      output.WriteInt32(SummaryDetailPosition);
    }
    if (HasSummaryDistancePosition) {
      output.WriteRawTag(64);
      output.WriteInt32(SummaryDistancePosition);
    }
    if (HasSummarySpeedPosition) {
      output.WriteRawTag(72);
      output.WriteInt32(SummarySpeedPosition);
    }
    if (HasSummaryDurationPosition) {
      output.WriteRawTag(80);
      output.WriteInt32(SummaryDurationPosition);
    }
    if (HasSummaryTimePosition) {
      output.WriteRawTag(88);
      output.WriteInt32(SummaryTimePosition);
    }
    if (HasSelectionSpeedPosition) {
      output.WriteRawTag(96);
      output.WriteInt32(SelectionSpeedPosition);
    }
    if (HasSelectionDistancePosition) {
      output.WriteRawTag(104);
      output.WriteInt32(SelectionDistancePosition);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasRunningDistancePosition) {
      output.WriteRawTag(8);
      output.WriteInt32(RunningDistancePosition);
    }
    if (HasRunningSpeedPosition) {
      output.WriteRawTag(16);
      output.WriteInt32(RunningSpeedPosition);
    }
    if (HasRunningCaloriesPosition) {
      output.WriteRawTag(24);
      output.WriteInt32(RunningCaloriesPosition);
    }
    if (HasRunningHeartRatePosition) {
      output.WriteRawTag(32);
      output.WriteInt32(RunningHeartRatePosition);
    }
    if (HasRunningDurationPosition) {
      output.WriteRawTag(40);
      output.WriteInt32(RunningDurationPosition);
    }
    if (HasRunningTimePosition) {
      output.WriteRawTag(48);
      output.WriteInt32(RunningTimePosition);
    }
    if (HasSummaryDetailPosition) {
      output.WriteRawTag(56);
      output.WriteInt32(SummaryDetailPosition);
    }
    if (HasSummaryDistancePosition) {
      output.WriteRawTag(64);
      output.WriteInt32(SummaryDistancePosition);
    }
    if (HasSummarySpeedPosition) {
      output.WriteRawTag(72);
      output.WriteInt32(SummarySpeedPosition);
    }
    if (HasSummaryDurationPosition) {
      output.WriteRawTag(80);
      output.WriteInt32(SummaryDurationPosition);
    }
    if (HasSummaryTimePosition) {
      output.WriteRawTag(88);
      output.WriteInt32(SummaryTimePosition);
    }
    if (HasSelectionSpeedPosition) {
      output.WriteRawTag(96);
      output.WriteInt32(SelectionSpeedPosition);
    }
    if (HasSelectionDistancePosition) {
      output.WriteRawTag(104);
      output.WriteInt32(SelectionDistancePosition);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasRunningDistancePosition) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(RunningDistancePosition);
    }
    if (HasRunningSpeedPosition) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(RunningSpeedPosition);
    }
    if (HasRunningCaloriesPosition) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(RunningCaloriesPosition);
    }
    if (HasRunningHeartRatePosition) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(RunningHeartRatePosition);
    }
    if (HasRunningDurationPosition) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(RunningDurationPosition);
    }
    if (HasRunningTimePosition) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(RunningTimePosition);
    }
    if (HasSummaryDetailPosition) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(SummaryDetailPosition);
    }
    if (HasSummaryDistancePosition) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(SummaryDistancePosition);
    }
    if (HasSummarySpeedPosition) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(SummarySpeedPosition);
    }
    if (HasSummaryDurationPosition) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(SummaryDurationPosition);
    }
    if (HasSummaryTimePosition) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(SummaryTimePosition);
    }
    if (HasSelectionSpeedPosition) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(SelectionSpeedPosition);
    }
    if (HasSelectionDistancePosition) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(SelectionDistancePosition);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(RunningTypePositionMappingData other) {
    if (other == null) {
      return;
    }
    if (other.HasRunningDistancePosition) {
      RunningDistancePosition = other.RunningDistancePosition;
    }
    if (other.HasRunningSpeedPosition) {
      RunningSpeedPosition = other.RunningSpeedPosition;
    }
    if (other.HasRunningCaloriesPosition) {
      RunningCaloriesPosition = other.RunningCaloriesPosition;
    }
    if (other.HasRunningHeartRatePosition) {
      RunningHeartRatePosition = other.RunningHeartRatePosition;
    }
    if (other.HasRunningDurationPosition) {
      RunningDurationPosition = other.RunningDurationPosition;
    }
    if (other.HasRunningTimePosition) {
      RunningTimePosition = other.RunningTimePosition;
    }
    if (other.HasSummaryDetailPosition) {
      SummaryDetailPosition = other.SummaryDetailPosition;
    }
    if (other.HasSummaryDistancePosition) {
      SummaryDistancePosition = other.SummaryDistancePosition;
    }
    if (other.HasSummarySpeedPosition) {
      SummarySpeedPosition = other.SummarySpeedPosition;
    }
    if (other.HasSummaryDurationPosition) {
      SummaryDurationPosition = other.SummaryDurationPosition;
    }
    if (other.HasSummaryTimePosition) {
      SummaryTimePosition = other.SummaryTimePosition;
    }
    if (other.HasSelectionSpeedPosition) {
      SelectionSpeedPosition = other.SelectionSpeedPosition;
    }
    if (other.HasSelectionDistancePosition) {
      SelectionDistancePosition = other.SelectionDistancePosition;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          RunningDistancePosition = input.ReadInt32();
          break;
        }
        case 16: {
          RunningSpeedPosition = input.ReadInt32();
          break;
        }
        case 24: {
          RunningCaloriesPosition = input.ReadInt32();
          break;
        }
        case 32: {
          RunningHeartRatePosition = input.ReadInt32();
          break;
        }
        case 40: {
          RunningDurationPosition = input.ReadInt32();
          break;
        }
        case 48: {
          RunningTimePosition = input.ReadInt32();
          break;
        }
        case 56: {
          SummaryDetailPosition = input.ReadInt32();
          break;
        }
        case 64: {
          SummaryDistancePosition = input.ReadInt32();
          break;
        }
        case 72: {
          SummarySpeedPosition = input.ReadInt32();
          break;
        }
        case 80: {
          SummaryDurationPosition = input.ReadInt32();
          break;
        }
        case 88: {
          SummaryTimePosition = input.ReadInt32();
          break;
        }
        case 96: {
          SelectionSpeedPosition = input.ReadInt32();
          break;
        }
        case 104: {
          SelectionDistancePosition = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          RunningDistancePosition = input.ReadInt32();
          break;
        }
        case 16: {
          RunningSpeedPosition = input.ReadInt32();
          break;
        }
        case 24: {
          RunningCaloriesPosition = input.ReadInt32();
          break;
        }
        case 32: {
          RunningHeartRatePosition = input.ReadInt32();
          break;
        }
        case 40: {
          RunningDurationPosition = input.ReadInt32();
          break;
        }
        case 48: {
          RunningTimePosition = input.ReadInt32();
          break;
        }
        case 56: {
          SummaryDetailPosition = input.ReadInt32();
          break;
        }
        case 64: {
          SummaryDistancePosition = input.ReadInt32();
          break;
        }
        case 72: {
          SummarySpeedPosition = input.ReadInt32();
          break;
        }
        case 80: {
          SummaryDurationPosition = input.ReadInt32();
          break;
        }
        case 88: {
          SummaryTimePosition = input.ReadInt32();
          break;
        }
        case 96: {
          SelectionSpeedPosition = input.ReadInt32();
          break;
        }
        case 104: {
          SelectionDistancePosition = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
