// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: running_target_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from running_target_data.proto</summary>
public static partial class RunningTargetDataReflection {

  #region Descriptor
  /// <summary>File descriptor for running_target_data.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static RunningTargetDataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChlydW5uaW5nX3RhcmdldF9kYXRhLnByb3RvIlMKEVJ1bm5pbmdUYXJnZXRE",
          "YXRhEhEKBXNwZWVkGAEgASgJOgItMRIUCghkaXN0YW5jZRgCIAEoCToCLTES",
          "FQoNdHJhaW5pbmdfbW9kZRgDIAEoCQ=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::RunningTargetData), global::RunningTargetData.Parser, new[]{ "Speed", "Distance", "TrainingMode" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class RunningTargetData : pb::IMessage<RunningTargetData>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<RunningTargetData> _parser = new pb::MessageParser<RunningTargetData>(() => new RunningTargetData());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<RunningTargetData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RunningTargetDataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RunningTargetData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RunningTargetData(RunningTargetData other) : this() {
    speed_ = other.speed_;
    distance_ = other.distance_;
    trainingMode_ = other.trainingMode_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RunningTargetData Clone() {
    return new RunningTargetData(this);
  }

  /// <summary>Field number for the "speed" field.</summary>
  public const int SpeedFieldNumber = 1;
  private readonly static string SpeedDefaultValue = global::System.Text.Encoding.UTF8.GetString(global::System.Convert.FromBase64String("LTE="), 0, 2);

  private string speed_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Speed {
    get { return speed_ ?? SpeedDefaultValue; }
    set {
      speed_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "speed" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasSpeed {
    get { return speed_ != null; }
  }
  /// <summary>Clears the value of the "speed" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearSpeed() {
    speed_ = null;
  }

  /// <summary>Field number for the "distance" field.</summary>
  public const int DistanceFieldNumber = 2;
  private readonly static string DistanceDefaultValue = global::System.Text.Encoding.UTF8.GetString(global::System.Convert.FromBase64String("LTE="), 0, 2);

  private string distance_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Distance {
    get { return distance_ ?? DistanceDefaultValue; }
    set {
      distance_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "distance" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasDistance {
    get { return distance_ != null; }
  }
  /// <summary>Clears the value of the "distance" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearDistance() {
    distance_ = null;
  }

  /// <summary>Field number for the "training_mode" field.</summary>
  public const int TrainingModeFieldNumber = 3;
  private readonly static string TrainingModeDefaultValue = "";

  private string trainingMode_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string TrainingMode {
    get { return trainingMode_ ?? TrainingModeDefaultValue; }
    set {
      trainingMode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "training_mode" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasTrainingMode {
    get { return trainingMode_ != null; }
  }
  /// <summary>Clears the value of the "training_mode" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearTrainingMode() {
    trainingMode_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as RunningTargetData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(RunningTargetData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Speed != other.Speed) return false;
    if (Distance != other.Distance) return false;
    if (TrainingMode != other.TrainingMode) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasSpeed) hash ^= Speed.GetHashCode();
    if (HasDistance) hash ^= Distance.GetHashCode();
    if (HasTrainingMode) hash ^= TrainingMode.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasSpeed) {
      output.WriteRawTag(10);
      output.WriteString(Speed);
    }
    if (HasDistance) {
      output.WriteRawTag(18);
      output.WriteString(Distance);
    }
    if (HasTrainingMode) {
      output.WriteRawTag(26);
      output.WriteString(TrainingMode);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasSpeed) {
      output.WriteRawTag(10);
      output.WriteString(Speed);
    }
    if (HasDistance) {
      output.WriteRawTag(18);
      output.WriteString(Distance);
    }
    if (HasTrainingMode) {
      output.WriteRawTag(26);
      output.WriteString(TrainingMode);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasSpeed) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Speed);
    }
    if (HasDistance) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Distance);
    }
    if (HasTrainingMode) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(TrainingMode);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(RunningTargetData other) {
    if (other == null) {
      return;
    }
    if (other.HasSpeed) {
      Speed = other.Speed;
    }
    if (other.HasDistance) {
      Distance = other.Distance;
    }
    if (other.HasTrainingMode) {
      TrainingMode = other.TrainingMode;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Speed = input.ReadString();
          break;
        }
        case 18: {
          Distance = input.ReadString();
          break;
        }
        case 26: {
          TrainingMode = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Speed = input.ReadString();
          break;
        }
        case 18: {
          Distance = input.ReadString();
          break;
        }
        case 26: {
          TrainingMode = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
