// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: running_place_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from running_place_data.proto</summary>
public static partial class RunningPlaceDataReflection {

  #region Descriptor
  /// <summary>File descriptor for running_place_data.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static RunningPlaceDataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChhydW5uaW5nX3BsYWNlX2RhdGEucHJvdG8iiQEKEFJ1bm5pbmdQbGFjZURh",
          "dGESFAoIcGxhY2VfaWQYASABKAU6Ai0xEhIKCGZhY2lsaXR5GAIgASgJOgAS",
          "EgoIbG9jYXRpb24YAyABKAk6ABIPCgVsZXZlbBgEIAEoCToAEhIKCGRpc3Rh",
          "bmNlGAUgASgJOgASEgoIcG9zaXRpb24YBiABKAk6AA=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::RunningPlaceData), global::RunningPlaceData.Parser, new[]{ "PlaceId", "Facility", "Location", "Level", "Distance", "Position" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class RunningPlaceData : pb::IMessage<RunningPlaceData>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<RunningPlaceData> _parser = new pb::MessageParser<RunningPlaceData>(() => new RunningPlaceData());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<RunningPlaceData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RunningPlaceDataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RunningPlaceData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RunningPlaceData(RunningPlaceData other) : this() {
    _hasBits0 = other._hasBits0;
    placeId_ = other.placeId_;
    facility_ = other.facility_;
    location_ = other.location_;
    level_ = other.level_;
    distance_ = other.distance_;
    position_ = other.position_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RunningPlaceData Clone() {
    return new RunningPlaceData(this);
  }

  /// <summary>Field number for the "place_id" field.</summary>
  public const int PlaceIdFieldNumber = 1;
  private readonly static int PlaceIdDefaultValue = -1;

  private int placeId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int PlaceId {
    get { if ((_hasBits0 & 1) != 0) { return placeId_; } else { return PlaceIdDefaultValue; } }
    set {
      _hasBits0 |= 1;
      placeId_ = value;
    }
  }
  /// <summary>Gets whether the "place_id" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasPlaceId {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "place_id" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearPlaceId() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "facility" field.</summary>
  public const int FacilityFieldNumber = 2;
  private readonly static string FacilityDefaultValue = "";

  private string facility_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Facility {
    get { return facility_ ?? FacilityDefaultValue; }
    set {
      facility_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "facility" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasFacility {
    get { return facility_ != null; }
  }
  /// <summary>Clears the value of the "facility" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearFacility() {
    facility_ = null;
  }

  /// <summary>Field number for the "location" field.</summary>
  public const int LocationFieldNumber = 3;
  private readonly static string LocationDefaultValue = "";

  private string location_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Location {
    get { return location_ ?? LocationDefaultValue; }
    set {
      location_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "location" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasLocation {
    get { return location_ != null; }
  }
  /// <summary>Clears the value of the "location" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearLocation() {
    location_ = null;
  }

  /// <summary>Field number for the "level" field.</summary>
  public const int LevelFieldNumber = 4;
  private readonly static string LevelDefaultValue = "";

  private string level_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Level {
    get { return level_ ?? LevelDefaultValue; }
    set {
      level_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "level" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasLevel {
    get { return level_ != null; }
  }
  /// <summary>Clears the value of the "level" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearLevel() {
    level_ = null;
  }

  /// <summary>Field number for the "distance" field.</summary>
  public const int DistanceFieldNumber = 5;
  private readonly static string DistanceDefaultValue = "";

  private string distance_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Distance {
    get { return distance_ ?? DistanceDefaultValue; }
    set {
      distance_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "distance" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasDistance {
    get { return distance_ != null; }
  }
  /// <summary>Clears the value of the "distance" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearDistance() {
    distance_ = null;
  }

  /// <summary>Field number for the "position" field.</summary>
  public const int PositionFieldNumber = 6;
  private readonly static string PositionDefaultValue = "";

  private string position_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Position {
    get { return position_ ?? PositionDefaultValue; }
    set {
      position_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "position" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasPosition {
    get { return position_ != null; }
  }
  /// <summary>Clears the value of the "position" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearPosition() {
    position_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as RunningPlaceData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(RunningPlaceData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (PlaceId != other.PlaceId) return false;
    if (Facility != other.Facility) return false;
    if (Location != other.Location) return false;
    if (Level != other.Level) return false;
    if (Distance != other.Distance) return false;
    if (Position != other.Position) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasPlaceId) hash ^= PlaceId.GetHashCode();
    if (HasFacility) hash ^= Facility.GetHashCode();
    if (HasLocation) hash ^= Location.GetHashCode();
    if (HasLevel) hash ^= Level.GetHashCode();
    if (HasDistance) hash ^= Distance.GetHashCode();
    if (HasPosition) hash ^= Position.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasPlaceId) {
      output.WriteRawTag(8);
      output.WriteInt32(PlaceId);
    }
    if (HasFacility) {
      output.WriteRawTag(18);
      output.WriteString(Facility);
    }
    if (HasLocation) {
      output.WriteRawTag(26);
      output.WriteString(Location);
    }
    if (HasLevel) {
      output.WriteRawTag(34);
      output.WriteString(Level);
    }
    if (HasDistance) {
      output.WriteRawTag(42);
      output.WriteString(Distance);
    }
    if (HasPosition) {
      output.WriteRawTag(50);
      output.WriteString(Position);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasPlaceId) {
      output.WriteRawTag(8);
      output.WriteInt32(PlaceId);
    }
    if (HasFacility) {
      output.WriteRawTag(18);
      output.WriteString(Facility);
    }
    if (HasLocation) {
      output.WriteRawTag(26);
      output.WriteString(Location);
    }
    if (HasLevel) {
      output.WriteRawTag(34);
      output.WriteString(Level);
    }
    if (HasDistance) {
      output.WriteRawTag(42);
      output.WriteString(Distance);
    }
    if (HasPosition) {
      output.WriteRawTag(50);
      output.WriteString(Position);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasPlaceId) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlaceId);
    }
    if (HasFacility) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Facility);
    }
    if (HasLocation) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Location);
    }
    if (HasLevel) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Level);
    }
    if (HasDistance) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Distance);
    }
    if (HasPosition) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Position);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(RunningPlaceData other) {
    if (other == null) {
      return;
    }
    if (other.HasPlaceId) {
      PlaceId = other.PlaceId;
    }
    if (other.HasFacility) {
      Facility = other.Facility;
    }
    if (other.HasLocation) {
      Location = other.Location;
    }
    if (other.HasLevel) {
      Level = other.Level;
    }
    if (other.HasDistance) {
      Distance = other.Distance;
    }
    if (other.HasPosition) {
      Position = other.Position;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          PlaceId = input.ReadInt32();
          break;
        }
        case 18: {
          Facility = input.ReadString();
          break;
        }
        case 26: {
          Location = input.ReadString();
          break;
        }
        case 34: {
          Level = input.ReadString();
          break;
        }
        case 42: {
          Distance = input.ReadString();
          break;
        }
        case 50: {
          Position = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          PlaceId = input.ReadInt32();
          break;
        }
        case 18: {
          Facility = input.ReadString();
          break;
        }
        case 26: {
          Location = input.ReadString();
          break;
        }
        case 34: {
          Level = input.ReadString();
          break;
        }
        case 42: {
          Distance = input.ReadString();
          break;
        }
        case 50: {
          Position = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
