// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: running_live_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from running_live_data.proto</summary>
public static partial class RunningLiveDataReflection {

  #region Descriptor
  /// <summary>File descriptor for running_live_data.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static RunningLiveDataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChdydW5uaW5nX2xpdmVfZGF0YS5wcm90byK3AQoPUnVubmluZ0xpdmVEYXRh",
          "EhIKCGRpc3RhbmNlGAEgASgJOgASFAoKaGVhcnRfcmF0ZRgCIAEoCToAEg8K",
          "BXNwZWVkGAMgASgJOgASEgoIY2Fsb3JpZXMYBCABKAk6ABISCghkdXJhdGlv",
          "bhgFIAEoCToAEg4KBHRpbWUYBiABKAk6ABIVCgtpbnN0cnVjdGlvbhgHIAEo",
          "CToAEhoKC2F1ZGlvX2luc3RyGAggASgIOgVmYWxzZQ=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::RunningLiveData), global::RunningLiveData.Parser, new[]{ "Distance", "HeartRate", "Speed", "Calories", "Duration", "Time", "Instruction", "AudioInstr" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class RunningLiveData : pb::IMessage<RunningLiveData>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<RunningLiveData> _parser = new pb::MessageParser<RunningLiveData>(() => new RunningLiveData());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<RunningLiveData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RunningLiveDataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RunningLiveData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RunningLiveData(RunningLiveData other) : this() {
    _hasBits0 = other._hasBits0;
    distance_ = other.distance_;
    heartRate_ = other.heartRate_;
    speed_ = other.speed_;
    calories_ = other.calories_;
    duration_ = other.duration_;
    time_ = other.time_;
    instruction_ = other.instruction_;
    audioInstr_ = other.audioInstr_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RunningLiveData Clone() {
    return new RunningLiveData(this);
  }

  /// <summary>Field number for the "distance" field.</summary>
  public const int DistanceFieldNumber = 1;
  private readonly static string DistanceDefaultValue = "";

  private string distance_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Distance {
    get { return distance_ ?? DistanceDefaultValue; }
    set {
      distance_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "distance" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasDistance {
    get { return distance_ != null; }
  }
  /// <summary>Clears the value of the "distance" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearDistance() {
    distance_ = null;
  }

  /// <summary>Field number for the "heart_rate" field.</summary>
  public const int HeartRateFieldNumber = 2;
  private readonly static string HeartRateDefaultValue = "";

  private string heartRate_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string HeartRate {
    get { return heartRate_ ?? HeartRateDefaultValue; }
    set {
      heartRate_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "heart_rate" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasHeartRate {
    get { return heartRate_ != null; }
  }
  /// <summary>Clears the value of the "heart_rate" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearHeartRate() {
    heartRate_ = null;
  }

  /// <summary>Field number for the "speed" field.</summary>
  public const int SpeedFieldNumber = 3;
  private readonly static string SpeedDefaultValue = "";

  private string speed_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Speed {
    get { return speed_ ?? SpeedDefaultValue; }
    set {
      speed_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "speed" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasSpeed {
    get { return speed_ != null; }
  }
  /// <summary>Clears the value of the "speed" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearSpeed() {
    speed_ = null;
  }

  /// <summary>Field number for the "calories" field.</summary>
  public const int CaloriesFieldNumber = 4;
  private readonly static string CaloriesDefaultValue = "";

  private string calories_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Calories {
    get { return calories_ ?? CaloriesDefaultValue; }
    set {
      calories_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "calories" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasCalories {
    get { return calories_ != null; }
  }
  /// <summary>Clears the value of the "calories" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearCalories() {
    calories_ = null;
  }

  /// <summary>Field number for the "duration" field.</summary>
  public const int DurationFieldNumber = 5;
  private readonly static string DurationDefaultValue = "";

  private string duration_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Duration {
    get { return duration_ ?? DurationDefaultValue; }
    set {
      duration_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "duration" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasDuration {
    get { return duration_ != null; }
  }
  /// <summary>Clears the value of the "duration" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearDuration() {
    duration_ = null;
  }

  /// <summary>Field number for the "time" field.</summary>
  public const int TimeFieldNumber = 6;
  private readonly static string TimeDefaultValue = "";

  private string time_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Time {
    get { return time_ ?? TimeDefaultValue; }
    set {
      time_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "time" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasTime {
    get { return time_ != null; }
  }
  /// <summary>Clears the value of the "time" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearTime() {
    time_ = null;
  }

  /// <summary>Field number for the "instruction" field.</summary>
  public const int InstructionFieldNumber = 7;
  private readonly static string InstructionDefaultValue = "";

  private string instruction_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Instruction {
    get { return instruction_ ?? InstructionDefaultValue; }
    set {
      instruction_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "instruction" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasInstruction {
    get { return instruction_ != null; }
  }
  /// <summary>Clears the value of the "instruction" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearInstruction() {
    instruction_ = null;
  }

  /// <summary>Field number for the "audio_instr" field.</summary>
  public const int AudioInstrFieldNumber = 8;
  private readonly static bool AudioInstrDefaultValue = false;

  private bool audioInstr_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool AudioInstr {
    get { if ((_hasBits0 & 1) != 0) { return audioInstr_; } else { return AudioInstrDefaultValue; } }
    set {
      _hasBits0 |= 1;
      audioInstr_ = value;
    }
  }
  /// <summary>Gets whether the "audio_instr" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasAudioInstr {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "audio_instr" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearAudioInstr() {
    _hasBits0 &= ~1;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as RunningLiveData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(RunningLiveData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Distance != other.Distance) return false;
    if (HeartRate != other.HeartRate) return false;
    if (Speed != other.Speed) return false;
    if (Calories != other.Calories) return false;
    if (Duration != other.Duration) return false;
    if (Time != other.Time) return false;
    if (Instruction != other.Instruction) return false;
    if (AudioInstr != other.AudioInstr) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasDistance) hash ^= Distance.GetHashCode();
    if (HasHeartRate) hash ^= HeartRate.GetHashCode();
    if (HasSpeed) hash ^= Speed.GetHashCode();
    if (HasCalories) hash ^= Calories.GetHashCode();
    if (HasDuration) hash ^= Duration.GetHashCode();
    if (HasTime) hash ^= Time.GetHashCode();
    if (HasInstruction) hash ^= Instruction.GetHashCode();
    if (HasAudioInstr) hash ^= AudioInstr.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasDistance) {
      output.WriteRawTag(10);
      output.WriteString(Distance);
    }
    if (HasHeartRate) {
      output.WriteRawTag(18);
      output.WriteString(HeartRate);
    }
    if (HasSpeed) {
      output.WriteRawTag(26);
      output.WriteString(Speed);
    }
    if (HasCalories) {
      output.WriteRawTag(34);
      output.WriteString(Calories);
    }
    if (HasDuration) {
      output.WriteRawTag(42);
      output.WriteString(Duration);
    }
    if (HasTime) {
      output.WriteRawTag(50);
      output.WriteString(Time);
    }
    if (HasInstruction) {
      output.WriteRawTag(58);
      output.WriteString(Instruction);
    }
    if (HasAudioInstr) {
      output.WriteRawTag(64);
      output.WriteBool(AudioInstr);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasDistance) {
      output.WriteRawTag(10);
      output.WriteString(Distance);
    }
    if (HasHeartRate) {
      output.WriteRawTag(18);
      output.WriteString(HeartRate);
    }
    if (HasSpeed) {
      output.WriteRawTag(26);
      output.WriteString(Speed);
    }
    if (HasCalories) {
      output.WriteRawTag(34);
      output.WriteString(Calories);
    }
    if (HasDuration) {
      output.WriteRawTag(42);
      output.WriteString(Duration);
    }
    if (HasTime) {
      output.WriteRawTag(50);
      output.WriteString(Time);
    }
    if (HasInstruction) {
      output.WriteRawTag(58);
      output.WriteString(Instruction);
    }
    if (HasAudioInstr) {
      output.WriteRawTag(64);
      output.WriteBool(AudioInstr);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasDistance) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Distance);
    }
    if (HasHeartRate) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(HeartRate);
    }
    if (HasSpeed) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Speed);
    }
    if (HasCalories) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Calories);
    }
    if (HasDuration) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Duration);
    }
    if (HasTime) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Time);
    }
    if (HasInstruction) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Instruction);
    }
    if (HasAudioInstr) {
      size += 1 + 1;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(RunningLiveData other) {
    if (other == null) {
      return;
    }
    if (other.HasDistance) {
      Distance = other.Distance;
    }
    if (other.HasHeartRate) {
      HeartRate = other.HeartRate;
    }
    if (other.HasSpeed) {
      Speed = other.Speed;
    }
    if (other.HasCalories) {
      Calories = other.Calories;
    }
    if (other.HasDuration) {
      Duration = other.Duration;
    }
    if (other.HasTime) {
      Time = other.Time;
    }
    if (other.HasInstruction) {
      Instruction = other.Instruction;
    }
    if (other.HasAudioInstr) {
      AudioInstr = other.AudioInstr;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Distance = input.ReadString();
          break;
        }
        case 18: {
          HeartRate = input.ReadString();
          break;
        }
        case 26: {
          Speed = input.ReadString();
          break;
        }
        case 34: {
          Calories = input.ReadString();
          break;
        }
        case 42: {
          Duration = input.ReadString();
          break;
        }
        case 50: {
          Time = input.ReadString();
          break;
        }
        case 58: {
          Instruction = input.ReadString();
          break;
        }
        case 64: {
          AudioInstr = input.ReadBool();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Distance = input.ReadString();
          break;
        }
        case 18: {
          HeartRate = input.ReadString();
          break;
        }
        case 26: {
          Speed = input.ReadString();
          break;
        }
        case 34: {
          Calories = input.ReadString();
          break;
        }
        case 42: {
          Duration = input.ReadString();
          break;
        }
        case 50: {
          Time = input.ReadString();
          break;
        }
        case 58: {
          Instruction = input.ReadString();
          break;
        }
        case 64: {
          AudioInstr = input.ReadBool();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
