// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: running_summary_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from running_summary_data.proto</summary>
public static partial class RunningSummaryDataReflection {

  #region Descriptor
  /// <summary>File descriptor for running_summary_data.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static RunningSummaryDataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChpydW5uaW5nX3N1bW1hcnlfZGF0YS5wcm90byJ+ChJSdW5uaW5nU3VtbWFy",
          "eURhdGESEAoGZGV0YWlsGAEgASgJOgASEgoIZGlzdGFuY2UYAiABKAk6ABIP",
          "CgVzcGVlZBgDIAEoCToAEhIKCGR1cmF0aW9uGAQgASgJOgASDQoFaW1hZ2UY",
          "BSABKAwSDgoEdGltZRgGIAEoCToA"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::RunningSummaryData), global::RunningSummaryData.Parser, new[]{ "Detail", "Distance", "Speed", "Duration", "Image", "Time" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class RunningSummaryData : pb::IMessage<RunningSummaryData>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<RunningSummaryData> _parser = new pb::MessageParser<RunningSummaryData>(() => new RunningSummaryData());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<RunningSummaryData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RunningSummaryDataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RunningSummaryData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RunningSummaryData(RunningSummaryData other) : this() {
    detail_ = other.detail_;
    distance_ = other.distance_;
    speed_ = other.speed_;
    duration_ = other.duration_;
    image_ = other.image_;
    time_ = other.time_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RunningSummaryData Clone() {
    return new RunningSummaryData(this);
  }

  /// <summary>Field number for the "detail" field.</summary>
  public const int DetailFieldNumber = 1;
  private readonly static string DetailDefaultValue = "";

  private string detail_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Detail {
    get { return detail_ ?? DetailDefaultValue; }
    set {
      detail_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "detail" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasDetail {
    get { return detail_ != null; }
  }
  /// <summary>Clears the value of the "detail" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearDetail() {
    detail_ = null;
  }

  /// <summary>Field number for the "distance" field.</summary>
  public const int DistanceFieldNumber = 2;
  private readonly static string DistanceDefaultValue = "";

  private string distance_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Distance {
    get { return distance_ ?? DistanceDefaultValue; }
    set {
      distance_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "distance" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasDistance {
    get { return distance_ != null; }
  }
  /// <summary>Clears the value of the "distance" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearDistance() {
    distance_ = null;
  }

  /// <summary>Field number for the "speed" field.</summary>
  public const int SpeedFieldNumber = 3;
  private readonly static string SpeedDefaultValue = "";

  private string speed_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Speed {
    get { return speed_ ?? SpeedDefaultValue; }
    set {
      speed_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "speed" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasSpeed {
    get { return speed_ != null; }
  }
  /// <summary>Clears the value of the "speed" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearSpeed() {
    speed_ = null;
  }

  /// <summary>Field number for the "duration" field.</summary>
  public const int DurationFieldNumber = 4;
  private readonly static string DurationDefaultValue = "";

  private string duration_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Duration {
    get { return duration_ ?? DurationDefaultValue; }
    set {
      duration_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "duration" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasDuration {
    get { return duration_ != null; }
  }
  /// <summary>Clears the value of the "duration" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearDuration() {
    duration_ = null;
  }

  /// <summary>Field number for the "image" field.</summary>
  public const int ImageFieldNumber = 5;
  private readonly static pb::ByteString ImageDefaultValue = pb::ByteString.Empty;

  private pb::ByteString image_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString Image {
    get { return image_ ?? ImageDefaultValue; }
    set {
      image_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "image" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasImage {
    get { return image_ != null; }
  }
  /// <summary>Clears the value of the "image" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearImage() {
    image_ = null;
  }

  /// <summary>Field number for the "time" field.</summary>
  public const int TimeFieldNumber = 6;
  private readonly static string TimeDefaultValue = "";

  private string time_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Time {
    get { return time_ ?? TimeDefaultValue; }
    set {
      time_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "time" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasTime {
    get { return time_ != null; }
  }
  /// <summary>Clears the value of the "time" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearTime() {
    time_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as RunningSummaryData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(RunningSummaryData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Detail != other.Detail) return false;
    if (Distance != other.Distance) return false;
    if (Speed != other.Speed) return false;
    if (Duration != other.Duration) return false;
    if (Image != other.Image) return false;
    if (Time != other.Time) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasDetail) hash ^= Detail.GetHashCode();
    if (HasDistance) hash ^= Distance.GetHashCode();
    if (HasSpeed) hash ^= Speed.GetHashCode();
    if (HasDuration) hash ^= Duration.GetHashCode();
    if (HasImage) hash ^= Image.GetHashCode();
    if (HasTime) hash ^= Time.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasDetail) {
      output.WriteRawTag(10);
      output.WriteString(Detail);
    }
    if (HasDistance) {
      output.WriteRawTag(18);
      output.WriteString(Distance);
    }
    if (HasSpeed) {
      output.WriteRawTag(26);
      output.WriteString(Speed);
    }
    if (HasDuration) {
      output.WriteRawTag(34);
      output.WriteString(Duration);
    }
    if (HasImage) {
      output.WriteRawTag(42);
      output.WriteBytes(Image);
    }
    if (HasTime) {
      output.WriteRawTag(50);
      output.WriteString(Time);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasDetail) {
      output.WriteRawTag(10);
      output.WriteString(Detail);
    }
    if (HasDistance) {
      output.WriteRawTag(18);
      output.WriteString(Distance);
    }
    if (HasSpeed) {
      output.WriteRawTag(26);
      output.WriteString(Speed);
    }
    if (HasDuration) {
      output.WriteRawTag(34);
      output.WriteString(Duration);
    }
    if (HasImage) {
      output.WriteRawTag(42);
      output.WriteBytes(Image);
    }
    if (HasTime) {
      output.WriteRawTag(50);
      output.WriteString(Time);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasDetail) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Detail);
    }
    if (HasDistance) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Distance);
    }
    if (HasSpeed) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Speed);
    }
    if (HasDuration) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Duration);
    }
    if (HasImage) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(Image);
    }
    if (HasTime) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Time);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(RunningSummaryData other) {
    if (other == null) {
      return;
    }
    if (other.HasDetail) {
      Detail = other.Detail;
    }
    if (other.HasDistance) {
      Distance = other.Distance;
    }
    if (other.HasSpeed) {
      Speed = other.Speed;
    }
    if (other.HasDuration) {
      Duration = other.Duration;
    }
    if (other.HasImage) {
      Image = other.Image;
    }
    if (other.HasTime) {
      Time = other.Time;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Detail = input.ReadString();
          break;
        }
        case 18: {
          Distance = input.ReadString();
          break;
        }
        case 26: {
          Speed = input.ReadString();
          break;
        }
        case 34: {
          Duration = input.ReadString();
          break;
        }
        case 42: {
          Image = input.ReadBytes();
          break;
        }
        case 50: {
          Time = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Detail = input.ReadString();
          break;
        }
        case 18: {
          Distance = input.ReadString();
          break;
        }
        case 26: {
          Speed = input.ReadString();
          break;
        }
        case 34: {
          Duration = input.ReadString();
          break;
        }
        case 42: {
          Image = input.ReadBytes();
          break;
        }
        case 50: {
          Time = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
