// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: learning_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from learning_data.proto</summary>
public static partial class LearningDataReflection {

  #region Descriptor
  /// <summary>File descriptor for learning_data.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static LearningDataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChNsZWFybmluZ19kYXRhLnByb3RvIkkKDExlYXJuaW5nRGF0YRIVCgtpbnN0",
          "cnVjdGlvbhgBIAEoCToAEhAKBmRldGFpbBgCIAEoCToAEhAKBnNwZWVjaBgD",
          "IAEoCToA"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::LearningData), global::LearningData.Parser, new[]{ "Instruction", "Detail", "Speech" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class LearningData : pb::IMessage<LearningData>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<LearningData> _parser = new pb::MessageParser<LearningData>(() => new LearningData());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<LearningData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::LearningDataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LearningData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LearningData(LearningData other) : this() {
    instruction_ = other.instruction_;
    detail_ = other.detail_;
    speech_ = other.speech_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LearningData Clone() {
    return new LearningData(this);
  }

  /// <summary>Field number for the "instruction" field.</summary>
  public const int InstructionFieldNumber = 1;
  private readonly static string InstructionDefaultValue = "";

  private string instruction_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Instruction {
    get { return instruction_ ?? InstructionDefaultValue; }
    set {
      instruction_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "instruction" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasInstruction {
    get { return instruction_ != null; }
  }
  /// <summary>Clears the value of the "instruction" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearInstruction() {
    instruction_ = null;
  }

  /// <summary>Field number for the "detail" field.</summary>
  public const int DetailFieldNumber = 2;
  private readonly static string DetailDefaultValue = "";

  private string detail_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Detail {
    get { return detail_ ?? DetailDefaultValue; }
    set {
      detail_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "detail" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasDetail {
    get { return detail_ != null; }
  }
  /// <summary>Clears the value of the "detail" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearDetail() {
    detail_ = null;
  }

  /// <summary>Field number for the "speech" field.</summary>
  public const int SpeechFieldNumber = 3;
  private readonly static string SpeechDefaultValue = "";

  private string speech_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Speech {
    get { return speech_ ?? SpeechDefaultValue; }
    set {
      speech_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "speech" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasSpeech {
    get { return speech_ != null; }
  }
  /// <summary>Clears the value of the "speech" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearSpeech() {
    speech_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as LearningData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(LearningData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Instruction != other.Instruction) return false;
    if (Detail != other.Detail) return false;
    if (Speech != other.Speech) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasInstruction) hash ^= Instruction.GetHashCode();
    if (HasDetail) hash ^= Detail.GetHashCode();
    if (HasSpeech) hash ^= Speech.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasInstruction) {
      output.WriteRawTag(10);
      output.WriteString(Instruction);
    }
    if (HasDetail) {
      output.WriteRawTag(18);
      output.WriteString(Detail);
    }
    if (HasSpeech) {
      output.WriteRawTag(26);
      output.WriteString(Speech);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasInstruction) {
      output.WriteRawTag(10);
      output.WriteString(Instruction);
    }
    if (HasDetail) {
      output.WriteRawTag(18);
      output.WriteString(Detail);
    }
    if (HasSpeech) {
      output.WriteRawTag(26);
      output.WriteString(Speech);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasInstruction) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Instruction);
    }
    if (HasDetail) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Detail);
    }
    if (HasSpeech) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Speech);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(LearningData other) {
    if (other == null) {
      return;
    }
    if (other.HasInstruction) {
      Instruction = other.Instruction;
    }
    if (other.HasDetail) {
      Detail = other.Detail;
    }
    if (other.HasSpeech) {
      Speech = other.Speech;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Instruction = input.ReadString();
          break;
        }
        case 18: {
          Detail = input.ReadString();
          break;
        }
        case 26: {
          Speech = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Instruction = input.ReadString();
          break;
        }
        case 18: {
          Detail = input.ReadString();
          break;
        }
        case 26: {
          Speech = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
