// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ma_metrics_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ma_metrics_type.proto</summary>
public static partial class MaMetricsTypeReflection {

  #region Descriptor
  /// <summary>File descriptor for ma_metrics_type.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static MaMetricsTypeReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChVtYV9tZXRyaWNzX3R5cGUucHJvdG8qWAoLTWV0cmljc1R5cGUSFQoRRU1J",
          "VF9QVU5DSF9USFJPV04QARIWChJFTUlUX1JFQUNUSU9OX1RJTUUQAhIaChZF",
          "TUlUX1NFUVVFTkNFX0NPTVBMRVRFEAM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MetricsType), }, null, null));
  }
  #endregion

}
#region Enums
public enum MetricsType {
  [pbr::OriginalName("EMIT_PUNCH_THROWN")] EmitPunchThrown = 1,
  [pbr::OriginalName("EMIT_REACTION_TIME")] EmitReactionTime = 2,
  [pbr::OriginalName("EMIT_SEQUENCE_COMPLETE")] EmitSequenceComplete = 3,
}

#endregion


#endregion Designer generated code
