// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ma_punch_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ma_punch_type.proto</summary>
public static partial class MaPunchTypeReflection {

  #region Descriptor
  /// <summary>File descriptor for ma_punch_type.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static MaPunchTypeReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChNtYV9wdW5jaF90eXBlLnByb3RvKkkKCVB1bmNoVHlwZRIMCghMRUZUX0pB",
          "QhAAEg0KCVJJR0hUX0pBQhABEg4KCkxFRlRfQ1JPU1MQAhIPCgtSSUdIVF9D",
          "Uk9TUxAD"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::PunchType), }, null, null));
  }
  #endregion

}
#region Enums
public enum PunchType {
  [pbr::OriginalName("LEFT_JAB")] LeftJab = 0,
  [pbr::OriginalName("RIGHT_JAB")] RightJab = 1,
  [pbr::OriginalName("LEFT_CROSS")] LeftCross = 2,
  [pbr::OriginalName("RIGHT_CROSS")] RightCross = 3,
}

#endregion


#endregion Designer generated code
