// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: highlight_point_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from highlight_point_data.proto</summary>
public static partial class HighlightPointDataReflection {

  #region Descriptor
  /// <summary>File descriptor for highlight_point_data.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static HighlightPointDataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChpoaWdobGlnaHRfcG9pbnRfZGF0YS5wcm90byJjChJIaWdobGlnaHRQb2lu",
          "dERhdGESEgoHd29ybGRfeBgCIAEoAToBMBISCgd3b3JsZF95GAMgASgBOgEw",
          "EhIKB3dvcmxkX3oYBCABKAE6ATASEQoHZGV0YWlscxgFIAEoCToA"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::HighlightPointData), global::HighlightPointData.Parser, new[]{ "WorldX", "WorldY", "WorldZ", "Details" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class HighlightPointData : pb::IMessage<HighlightPointData>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<HighlightPointData> _parser = new pb::MessageParser<HighlightPointData>(() => new HighlightPointData());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<HighlightPointData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::HighlightPointDataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public HighlightPointData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public HighlightPointData(HighlightPointData other) : this() {
    _hasBits0 = other._hasBits0;
    worldX_ = other.worldX_;
    worldY_ = other.worldY_;
    worldZ_ = other.worldZ_;
    details_ = other.details_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public HighlightPointData Clone() {
    return new HighlightPointData(this);
  }

  /// <summary>Field number for the "world_x" field.</summary>
  public const int WorldXFieldNumber = 2;
  private readonly static double WorldXDefaultValue = 0D;

  private double worldX_;
  /// <summary>
  ///  optional int64 time = 1 [default = -1];
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double WorldX {
    get { if ((_hasBits0 & 1) != 0) { return worldX_; } else { return WorldXDefaultValue; } }
    set {
      _hasBits0 |= 1;
      worldX_ = value;
    }
  }
  /// <summary>Gets whether the "world_x" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasWorldX {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "world_x" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearWorldX() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "world_y" field.</summary>
  public const int WorldYFieldNumber = 3;
  private readonly static double WorldYDefaultValue = 0D;

  private double worldY_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double WorldY {
    get { if ((_hasBits0 & 2) != 0) { return worldY_; } else { return WorldYDefaultValue; } }
    set {
      _hasBits0 |= 2;
      worldY_ = value;
    }
  }
  /// <summary>Gets whether the "world_y" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasWorldY {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "world_y" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearWorldY() {
    _hasBits0 &= ~2;
  }

  /// <summary>Field number for the "world_z" field.</summary>
  public const int WorldZFieldNumber = 4;
  private readonly static double WorldZDefaultValue = 0D;

  private double worldZ_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double WorldZ {
    get { if ((_hasBits0 & 4) != 0) { return worldZ_; } else { return WorldZDefaultValue; } }
    set {
      _hasBits0 |= 4;
      worldZ_ = value;
    }
  }
  /// <summary>Gets whether the "world_z" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasWorldZ {
    get { return (_hasBits0 & 4) != 0; }
  }
  /// <summary>Clears the value of the "world_z" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearWorldZ() {
    _hasBits0 &= ~4;
  }

  /// <summary>Field number for the "details" field.</summary>
  public const int DetailsFieldNumber = 5;
  private readonly static string DetailsDefaultValue = "";

  private string details_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Details {
    get { return details_ ?? DetailsDefaultValue; }
    set {
      details_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "details" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasDetails {
    get { return details_ != null; }
  }
  /// <summary>Clears the value of the "details" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearDetails() {
    details_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as HighlightPointData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(HighlightPointData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(WorldX, other.WorldX)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(WorldY, other.WorldY)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(WorldZ, other.WorldZ)) return false;
    if (Details != other.Details) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasWorldX) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(WorldX);
    if (HasWorldY) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(WorldY);
    if (HasWorldZ) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(WorldZ);
    if (HasDetails) hash ^= Details.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasWorldX) {
      output.WriteRawTag(17);
      output.WriteDouble(WorldX);
    }
    if (HasWorldY) {
      output.WriteRawTag(25);
      output.WriteDouble(WorldY);
    }
    if (HasWorldZ) {
      output.WriteRawTag(33);
      output.WriteDouble(WorldZ);
    }
    if (HasDetails) {
      output.WriteRawTag(42);
      output.WriteString(Details);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasWorldX) {
      output.WriteRawTag(17);
      output.WriteDouble(WorldX);
    }
    if (HasWorldY) {
      output.WriteRawTag(25);
      output.WriteDouble(WorldY);
    }
    if (HasWorldZ) {
      output.WriteRawTag(33);
      output.WriteDouble(WorldZ);
    }
    if (HasDetails) {
      output.WriteRawTag(42);
      output.WriteString(Details);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasWorldX) {
      size += 1 + 8;
    }
    if (HasWorldY) {
      size += 1 + 8;
    }
    if (HasWorldZ) {
      size += 1 + 8;
    }
    if (HasDetails) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Details);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(HighlightPointData other) {
    if (other == null) {
      return;
    }
    if (other.HasWorldX) {
      WorldX = other.WorldX;
    }
    if (other.HasWorldY) {
      WorldY = other.WorldY;
    }
    if (other.HasWorldZ) {
      WorldZ = other.WorldZ;
    }
    if (other.HasDetails) {
      Details = other.Details;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 17: {
          WorldX = input.ReadDouble();
          break;
        }
        case 25: {
          WorldY = input.ReadDouble();
          break;
        }
        case 33: {
          WorldZ = input.ReadDouble();
          break;
        }
        case 42: {
          Details = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 17: {
          WorldX = input.ReadDouble();
          break;
        }
        case 25: {
          WorldY = input.ReadDouble();
          break;
        }
        case 33: {
          WorldZ = input.ReadDouble();
          break;
        }
        case 42: {
          Details = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
